# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [100]:
three_arr = np.zeros(10)
three_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [101]:
three_arr.shape

(10,)

5. Print the type of the previous array in question 3

In [102]:
three_arr.dtype

dtype('float64')

6. Print the numpy version and the configuration


In [24]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/WinSOft---/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/WinSOft---/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/WinSOft---/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117

7. Print the dimension of the array in question 3


In [103]:
three_arr.ndim

1

8. Create a boolean array with all the True values

In [105]:
b = np.ones((2,2))
print(b == True)

[[ True  True]
 [ True  True]]


In [114]:
two_d = np.array([[1,2,3,4],[2,1,3,5]])
print(two_d)
print('dimension is ',two_d.ndim)

[[1 2 3 4]
 [2 1 3 5]]
dimension is  2


10. Create a three dimensional array



In [113]:
three_d = np.array([[[2,1,3,4],[2,6,7,8],[7,4,3,2],[1,7,8,2]]])
print(three_d)
print('dimension is ',three_d.ndim)

[[[2 1 3 4]
  [2 6 7 8]
  [7 4 3 2]
  [1 7 8 2]]]
demension is  3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [66]:
one_vector = ([2,3,4,5,6,7,8,9])
one_vector_reverse = np.flip(one_vector)
one_vector_reverse

array([9, 8, 7, 6, 5, 4, 3, 2])

12. Create a null vector of size 10 but the fifth value which is 1 

In [90]:
null_vec = np.zeros(10)
null_vec[5]=1
null_vec

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [93]:
identity_matrics = np.ones((3,3))
identity_matrics 


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [115]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print('this array type is ',arr.dtype)

this array type is  float64


# 15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [118]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr_into = arr1 * arr2
arr_into


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [88]:
arr_1_arr_2_compared = arr1 == arr2
arr_1_arr_2_compared


array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [151]:
arr_num = np.array([0,1,2,3,4,5,6,7,8,9])
arr_num[1:10:2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [152]:
arr_num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [164]:
arr = np.arange(10)
arr[5]=8
arr[6]=11
arr[7]=12
print(arr)



[ 0  1  2  3  4  8 11 12  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [173]:
two_2d = np.ones((2,2)) 
two_2d[1,1]=0
two_2d

array([[1., 1.],
       [1., 0.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [199]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d = np.where(arr2d >4, 20 ,arr2d)
arr2d


array([[ 1,  2,  3],
       [ 4, 20, 20],
       [20, 20, 20]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [204]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d = np.where(arr3d >0, 64 ,arr3d)
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[64, 64, 64],
        [64, 64, 64]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [211]:
two_dim = np.array([[0,1,2,3,4],[5,6,7,8,9]])
two_dim[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [212]:
two_dim = np.array([[0,1,2,3,4],[5,6,7,8,9]])
two_dim[1]

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [228]:
two_dim = np.array([[0,1,2,3,4],[5,6,7,8,9]])
two_dim[1,0]

5

26. Create a 10x10 array with random values and find the minimum and maximum values

In [242]:
my_random_arr = np.random.rand(10,10)
print('min',my_random_arr.min())
print('max',my_random_arr.max())

min 0.049435766996963615
max 0.9758102928456838


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [12]:
import numpy as np
j = np.array([1,2,3,2,3,4,3,4,5,6]) 
i = np.array([7,2,10,2,7,4,9,4,9,8])
comm = np.intersect1d(j,i)
comm

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [18]:
j = np.array([1,2,3,2,3,4,3,4,5,6]) 
i = np.array([7,2,10,2,7,4,9,4,9,8])
match = np.where(j == i)
match

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [114]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

print(data)
if data == names[2]:
    print("names're not equal to string-will")

[[ 0.63760504 -0.84597278  0.09184024  0.47440098]
 [ 1.364283    1.42712766  1.40099015 -0.61778105]
 [ 1.62504954  0.38386357  0.18254452 -0.31505421]
 [-0.17986522  1.62511939  1.73175212 -0.58587761]
 [-1.39875903  1.86337732 -2.16878204 -1.17605604]
 [-1.82213604  0.29790358  1.64493574  2.01938225]
 [-0.25017507 -0.85389754 -0.5130854   1.07861352]]


<ipython-input-114-eec89afae78c>:5: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if data == names[2]:


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [116]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

print(data)
if data == names[1:3]:
    print("names're not equal to string-will and joe")

[[-1.69717818 -0.34693777  0.51411401 -1.039135  ]
 [-0.96408735  0.07608724  0.64112948  0.20407949]
 [ 0.35664948 -0.14111254  0.97936233 -0.62459375]
 [ 0.77154722  0.75592095 -2.17016725 -2.03590762]
 [-0.49697473 -0.34444752 -0.65533092  0.12423632]
 [ 1.79042591  3.08674058  1.34342024 -0.82149082]
 [ 0.689094    0.30624087  0.17734168 -0.48436901]]


<ipython-input-116-adccf60c3995>:5: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if data == names[1:3]:


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [53]:
dec_num = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]],dtype=float)
dec_num

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [56]:
dec_num_two = np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,11],[13,14,15,16]]]],dtype=float)
dec_num_two

array([[[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 11.],
         [13., 14., 15., 16.]]]])

33. Swap axes of the array you created in Question 32

In [64]:
swamp_aray = np.swapaxes(dec_num_two,0,3)
swamp_aray

array([[[[ 1.],
         [ 5.],
         [ 9.],
         [13.]]],


       [[[ 2.],
         [ 6.],
         [10.],
         [14.]]],


       [[[ 3.],
         [ 7.],
         [11.],
         [15.]]],


       [[[ 4.],
         [ 8.],
         [11.],
         [16.]]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [83]:
ten_arr = np.array([1,2,3,4,5,6,7,8,9,10])
if ten_arr.any() <0.5:
    ten_arr = 0
else:
    finding_ten_arr = np.sqrt(ten_arr)
finding_ten_arr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [95]:
u = np.arange(12)
v = np.arange(12)
z = u.max()
z

11

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [121]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uni = np.unique(names, axis=0)
uni


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [28]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
rem_a = np.setdiff1d(a,b)
rem_a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [1]:
import numpy as np
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])
add = np.delete(sampleArray, 1 ,1)
sub_add = np.insert(add, 1 ,newColumn, axis =1)
sub_add

NameError: name 'numpy' is not defined

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [3]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.dot([a,b])

NameError: name 'a' is not defined

40. Generate a matrix of 20 random values and find its cumulative sum

In [29]:
arr_r = np.random.rand(21)
arr_r.sum()

10.688489109666008