# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

In [83]:
import numpy as  np
a = np.array([1, 2, 3, 4,5, 6, 7, 8, 9,10,11,12])
print('a Axes',a.ndim)
two_d = a.reshape(4,3)
print(two_d)
print('now axes is',two_d.ndim)

a Axes 1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
now axes is 2


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [86]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
c  = np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [87]:
e = np.array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])
f = np.array([5, 6, 7, 8, 9, 1, 1, 1, 1, 1])
g  = np.hstack((e,f))
g

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [89]:
m_flat = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
m_flat.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [105]:
h = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_h = h.reshape(2,3,2)
new_h

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [36]:
sqr_array = np.random.randn(5,5)
sqr_array ** 2

array([[5.69047890e-01, 2.18566171e+00, 3.53557170e+00, 1.86358611e+00,
        9.92148760e-02],
       [1.56931645e+00, 1.32395066e-01, 4.71578157e+00, 4.51373197e-01,
        4.77319301e-01],
       [1.60936604e-03, 7.11637139e+00, 9.97069005e-07, 5.09132030e-04,
        3.75953679e-01],
       [5.44875887e-02, 1.56979859e+00, 3.00490214e-02, 8.56485919e-02,
        1.36208168e+00],
       [1.70870721e-02, 1.28179726e+00, 2.68564951e-03, 1.19611900e+00,
        6.98495225e-04]])

## Question:8

### Create 5x6 an array and find the mean?

In [109]:
mean_array = np.random.randn(5,6)
print(mean_array)
new_mean_array = np.mean(mean_array)
new_mean_array

[[ 2.2105521   1.26510777 -1.75428019  0.20199939  0.62032889 -0.44714354]
 [ 0.85369634 -0.88858469  2.16267281 -0.31873537  0.8671708  -0.47695053]
 [ 0.19250819  1.08381322 -1.51617104 -0.20143266 -0.67169605 -0.27704791]
 [-0.68023693  1.1799763   1.95325158  0.56754772  1.33606003 -0.27686765]
 [-0.21830018  0.95087291  0.28119053 -2.15664688 -0.7127815   0.23274294]]


0.17875388034155099

## Question:9

### Find the standard deviation of the previous array in Q8?

In [110]:
std_of_mean_array = np.std(mean_array)
std_of_mean_array

1.0752580735826298

## Question:10

### Find the median of the previous array in Q8?

In [113]:
median_of_mean_array = np.median(mean_array)
median_of_mean_array

0.19725379184474376

## Question:11

### Find the transpose of the previous array in Q8?

In [121]:
np.transpose(mean_array)

array([[ 2.2105521 ,  0.85369634,  0.19250819, -0.68023693, -0.21830018],
       [ 1.26510777, -0.88858469,  1.08381322,  1.1799763 ,  0.95087291],
       [-1.75428019,  2.16267281, -1.51617104,  1.95325158,  0.28119053],
       [ 0.20199939, -0.31873537, -0.20143266,  0.56754772, -2.15664688],
       [ 0.62032889,  0.8671708 , -0.67169605,  1.33606003, -0.7127815 ],
       [-0.44714354, -0.47695053, -0.27704791, -0.27686765,  0.23274294]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [124]:
print(new_h)
new_h.diagonal(0,0,1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([[ 1,  9],
       [ 2, 10]])

## Question:13

### Find the determinant of the previous array in Q12?

In [128]:
det_array = np.array([[1,2],[3,4]])
found_det_array = np.linalg.det(det_array)
found_det_array

-2.0000000000000004

## Question:14

### Find the 5th and 95th percentile of an array?

In [130]:
per_array = np.array([[10,7,4],[3,2,1]])
found_per_array = np.percentile(per_array,50)
found_per_array

3.5

## Question:15

### How to find if a given array has any null values?

In [138]:
np.isnan(a)

array([[False, False, False, False, False],
       [False, False, False, False, False]])